const {
  ACCESS_PRIVATE_KEY = '',
  ACCESS_PUBLIC_KEY = '',
  ACCESS_TOKEN_EXP = '',
  APP_NAME = '',
  COMPANY_ADDRESS = '',
  COMPANY_EMAIL = '',
  COMPANY_NAME = '',
  COMPANY_PHONE = '',
  HOST = '',
  NODE_ENV = '',
  PORT = '',
  PROTOCOL = '',
  REFRESH_PRIVATE_KEY = '',
  REFRESH_PUBLIC_KEY = '',
  REFRESH_TOKEN_EXP = '',
  SENDER_EMAIL = '',
  SENDGRID_API_KEY = ''
} = process.env;

const environment = {
  ACCESS_PRIVATE_KEY,
  ACCESS_PUBLIC_KEY,
  ACCESS_TOKEN_EXP: Number(ACCESS_TOKEN_EXP),
  APP_NAME,
  BASE_URL: `${PROTOCOL}${HOST}`,
  COMPANY_ADDRESS,
  COMPANY_EMAIL,
  COMPANY_NAME,
  COMPANY_PHONE,
  HOST,
  NODE_ENV,
  PORT: Number(PORT),
  PROTOCOL,
  REFRESH_PRIVATE_KEY,
  REFRESH_PUBLIC_KEY,
  REFRESH_TOKEN_EXP: Number(REFRESH_TOKEN_EXP),
  SENDER_EMAIL,
  SENDGRID_API_KEY
};

export default environment;
